models/User.php
<?php
/**
 * @link http://zenothing.com/
*/

namespace app\models;


use app\behaviors\Journal;
use Exception;
use Yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\web\User as WebUser;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 * Class User
 * @property integer id
 * @property string name
 * @property string auth
 * @property string email
 * @property string code
 * @property string hash
 * @property string wallet
 * @property string perfect
 * @property string timezone
 * @property string country
 * @property string repeat
 * @property integer status
 * @property number account
 * @property integer duration
 * @property integer ref_name
 * @property resource data
 * @property array bundle
 *
 * @property User referral
 * @package app\models
 */
class User extends ActiveRecord implements IdentityInterface {

    const BLOCKED = 0;
    const ADMIN = 1;
    const PLAIN = 2;
    const MANAGER = 3;
    const TEAM = 4;

    private $_password;
    private $_info;
    public $repeat;

    public static function primaryKey() {
        return ['id'];
    }

    public static function statuses() {
        return [
            User::BLOCKED => Yii::t('app', 'Blocked'),
            User::ADMIN => Yii::t('app', 'Admin'),
            User::PLAIN => Yii::t('app', 'Registered'),
            User::MANAGER => Yii::t('app', 'Manager'),
            User::TEAM => Yii::t('app', 'Team')
        ];
    }

    public static $events = [
        'login' => 'Вход',
        'logout' => 'Выход',
        'login_fail' => 'Неудачная попытка входа',
    ];

    public function traceable() {
        return ['status', 'email', 'skype',  'perfect', 'account'];
    }

    public function url() {
        return ['user/view', 'name' => $this->name];
    }

    public function rules() {
        return [
            ['id', 'integer'],
            [['name', 'email', 'perfect', 'account'], 'required'],
            [['password', 'repeat'], 'required', 'on' => 'signup'],
            ['name', 'string', 'min' => 4, 'max' => 24],
            ['name', 'match', 'pattern' => '/^[a-z][a-z0-9_\-]+$/i', 'on' => 'signup'],
            [['name'], 'unique',
                'targetClass' => 'app\models\User',
                'message' => Yii::t('app', 'This value has already been taken')],
            ['email', 'email'],
            ['perfect', 'match', 'pattern' => '/^U\d{7}$/', 'message' =>
                Yii::t('app', 'The wallet should looks like U1234567')],
            ['skype', 'match', 'pattern' => '/^[a-zA-Z][a-zA-Z0-9\.,\-_]{5,31}$/'],
            [['skype', 'timezone', 'country', 'phone', 'forename', 'surname', 'name', 'email', 'perfect'],
                'filter', 'filter' => 'trim'],
            ['duration', 'integer', 'min' => 0, 'max' => 60 * 24 * 7],
            ['timezone', 'in', 'range' => timezone_identifiers_list()],
            ['repeat', 'compare', 'compareAttribute' => 'password'],
            [['forename', 'surname'], 'string', 'min' => 2, 'max' => 24],
            ['phone', 'match', 'pattern' => '/^\d{9,16}$/']
        ];
    }

    public function scenarios() {
        return [
            'default' => ['email', 'skype', 'duration', 'country', 'timezone', 'phone', 'forename', 'surname'],
            'signup'  => ['name', 'email', 'skype', 'perfect', 'password', 'repeat', 'ref_name'],
            'admin'   => ['name', 'email', 'skype', 'perfect', 'account', 'status',
                'duration', 'country', 'timezone', 'phone', 'forename', 'surname', 'ref_name'],
        ];
    }

    public function attributeLabels() {
        return [
            'name' => Yii::t('app', 'Username'),
            'email' => Yii::t('app', 'Email'),
            'password' => Yii::t('app', 'Password'),
            'repeat' => Yii::t('app', 'Repeat'),
            'status' => Yii::t('app', 'Status'),
            'account' => Yii::t('app', 'Account'),
            'skype' => Yii::t('app', 'Skype'),
            'perfect' => Yii::t('app', 'Perfect Money wallet'),
            'duration' => Yii::t('app', 'Session duration (in minutes)'),
            'timezone' => Yii::t('app', 'Timezone'),
            'country' => Yii::t('app', 'Country'),
            'phone' => Yii::t('app', 'Phone'),
            'forename' => Yii::t('app', 'Forename'),
            'surname' => Yii::t('app', 'Surname'),
        ];
    }

    public function behaviors() {
        return [
            Journal::class
        ];
    }

    public function init() {
        parent::init();
        if (isset(Yii::$app->user)
            && Yii::$app->user instanceof WebUser
            && !Yii::$app->user->getIsGuest()
            && static::ADMIN == Yii::$app->user->identity->status) {
            $this->scenario = 'admin';
        }
    }

    /**
     * @param string $id
     * @return User
     */
    public static function findIdentity($id) {
        return parent::findOne(['id' => $id]);
    }

    public static function findIdentityByAccessToken($token, $type = null) {
        throw new Exception('Not implemented findIdentityByAccessToken');
    }

    public function getId() {
        return $this->id;
    }

    public function getAuthKey() {
        return $this->auth;
    }

    public function validateAuthKey($authKey) {
        return $authKey == $this->auth;
    }

    public function validatePassword($password) {
        return password_verify($password, $this->hash);
    }

    public function getPassword() {
        return $this->_password;
    }

    public function setPassword($value) {
        $this->hash = password_hash($value, PASSWORD_DEFAULT);
        $this->_password = $value;
    }

    public function generateAuthKey() {
        $this->auth = Yii::$app->security->generateRandomString(64);
    }

    public function generateCode() {
        $this->code = Yii::$app->security->generateRandomString(64);
    }

    public function isTeam() {
        return static::TEAM == $this->status || static::ADMIN == $this->status || static::MANAGER == $this->status;
    }

    public function isManager() {
        return static::ADMIN == $this->status || static::MANAGER == $this->status;
    }

    public function isAdmin() {
        return static::ADMIN == $this->status;
    }

    public function __toString() {
        return $this->name;
    }

    public function sendEmail($params)
    {
        $template = Yii::getAlias('@app') . "/views/mail.php";
        return Yii::$app->mailer->compose()
            ->setTo($this->email)
            ->setFrom(['chinastroyinvest@gmail.com' => Yii::$app->name])
            ->setSubject($params['subject'])
            ->setHtmlBody(Yii::$app->view->renderFile($template, $params))
            ->send();
    }

    public function canLogin() {
        return Record::find()->andWhere([
            'object_id' => $this->id,
            'event' => 'login_fail'
        ])
            ->andWhere('(NOW() - "time") < interval \'5 minutes\'')
            ->count() < 30;
    }

    public function getBundle() {
        if (!$this->_info) {
            $this->_info = unserialize(stream_get_contents($this->data));
        }
        return $this->_info;
    }

    public function setBundle($value) {
        $value = empty($value) ? null : serialize($value);
        $this->data = $value;
        $this->_info = $value;
    }

    public function setBundleFromAttributes($names, $restore = false) {
        $bundle = [];
        foreach($names as $name) {
            $bundle[$name] = $this->$name;
            if ($restore) {
                $this->$name = $this->getOldAttribute($name);
            }
        }
        $this->setBundle($bundle);
    }

    public function journalView() {
        return __DIR__ . '/../views/user/journal.php';
    }

    public function getReferral() {
        return $this->hasOne(User::class, ['name' => 'ref_name']);
    }
}

controllers/UserController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\behaviors\Access;
use app\behaviors\Journal;
use app\models\LoginForm;
use app\models\Message;
use app\models\Password;
use app\models\Record;
use app\models\ResetRequest;
use app\helpers\SQL;
use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use yii\base\InvalidParamException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class UserController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['index', 'view', 'update'],
                'manager' => ['complete', 'account'],
                'admin' => ['delete']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => Yii::$app->user->identity->isManager() ? null : Yii::$app->user->identity
        ]);
    }

    public function actionView($name = null) {
        if (!$name && Yii::$app->user->isGuest) {
            throw new InvalidParamException();
        }

        $model = $name ? $this->findModel($name) : Yii::$app->user->identity;
        if (Yii::$app->user->isGuest
            || (!Yii::$app->user->identity->isManager() && Yii::$app->user->identity->name != $model->name)) {
            throw new ForbiddenHttpException();
        }

        if ($model->name == Yii::$app->user->identity->name) {
            Message::show();
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCreate() {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($name) {
        $model = $this->findModel($name);

        if ($model->name != Yii::$app->user->identity->name && !Yii::$app->user->identity->isAdmin()) {
            throw new ForbiddenHttpException('Forbidden');
        }

        if ($model->load(Yii::$app->request->post())) {
            if (!Yii::$app->user->identity->isAdmin()) {
                if ($model->isAttributeChanged('email', false)) {
                    $model->generateCode();
                    $url = Url::to(['email', 'code' => $model->code], true);
                    $model->sendEmail([
                        'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Email confirmation'),
                        'content' => Yii::t('app', 'To confirm your email click on the <a href="{url}">link</a>', [
                            'url' => $url,
                        ])
                    ]);
                    $model->setBundle(['email' => $model->email]);
                    $model->email = $model->getOldAttribute('email');
                    Yii::$app->session->setFlash('info', Yii::t('app', 'The new email address will be changed after you confirm it'));
                }
                if ($model->isAttributeChanged('perfect', false)) {
                    $model->perfect = $model->getOldAttribute('perfect');
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Wallet can change admin only'));
                }
            }

            if ('Europe/Moscow' == $model->timezone) {
                $model->timezone = null;
            }

            foreach(['skype', 'country', 'phone', 'forename', 'surname'] as $name) {
                if (empty($model->$name)) {
                    $model->$name = null;
                }
            }

            if (Yii::$app->user->identity->name == $model->name && $model->isAttributeChanged('timezone', false)) {
                $_SESSION['timezone'] = $model->timezone;
            }

            if ($model->save()) {
                return $this->redirect(['view', 'name' => $model->name]);
            }
        }

        if (!$model->timezone) {
            $model->timezone = 'Europe/Moscow';
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($name) {
        $this->findModel($name)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param string $name
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($name) {
        if (($model = User::findOne(['name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSignup($ref_name = null) {
        $model = new User([
            'scenario' => 'signup'
        ]);
        if (!$ref_name && Yii::$app->session->has('ref_name')) {
            $ref_name = Yii::$app->session->get('ref_name');
        }
        if ($ref_name) {
            $model->ref_name = $ref_name;
            if (!Yii::$app->session->has('ref_name')) {
                Yii::$app->session->set('ref_name', $ref_name);
            }
        }
        if (preg_match('|U\w{7}|', $model->name)) {
            $model->addError('name', Yii::t('app', Yii::t('app', 'Username cannot be in the format of Perfect Money wallet')));
        }
        elseif ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->generateAuthKey();
            $model->status = User::PLAIN;
            if (!$model->ref_name) {
                $model->ref_name = 'Alex-Shild123';
            }
            if ($model->save(false)) {
                Yii::$app->user->login($model);
                return $this->redirect(['user/view']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionLogin() {
        $model = new LoginForm([
            'duration' => 60 * 24
        ]);

        if ($model->load(Yii::$app->request->post())) {
            $user = $model->getUser();
            if ($user) {
                if (empty($user->hash)) {
                    Yii::$app->session->setFlash('error', Yii::t('app',
                        Yii::t('app', 'Your account is not activated. Check your email')));
                }
                else {
                    $can = $user->canLogin();
                    if ($can && $user->validatePassword($model->password)) {
                        if ($user->status > 0) {
                            if (empty($user->auth)) {
                                $user->generateAuthKey();
                                $user->save();
                            }

                            if ('admin' == Yii::$app->layout && !$user->isManager()) {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'You cannot manage site'));
                            }
                            elseif (Yii::$app->user->login($user, $model->remember ? $model->duration * 60 : 0)) {
                                if ('admin' == Yii::$app->layout) {
                                    return $this->redirect(['/home/statistics']);
                                }
                                else {
                                    return $this->redirect(['view']);
                                }
                            }
                            else {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
                            }
                        } else {
                            Yii::$app->session->setFlash('error', Yii::t('app', Yii::t('app', 'Your account is blocked')));
                        }
                    } else {
                        Journal::write('user', 'login_fail', $user->id);
                        if ($can) {
                            Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
                        } else {
                            $record = Record::find()->where([
                                'object_id' => $user->id,
                                'event' => 'login_fail'
                            ])->orderBy(['time' => SORT_DESC])->one();
                            Yii::$app->session->setFlash('error',
                                Yii::t('app', 'You have exceeded the maximum number of login attempts, you will be able to enter after {time}', [
                                    'time' => $record->time
                                ]));
                        }
                    }
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->redirect(['home/index']);
    }

    public function actionEmail($code) {
        /** @var User $user */
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
            $user = User::findOne(['name' => $code]);
        }
        else {

views/user/_form.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use app\widgets\Ext;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */

function submit($label) {
    return Html::submitButton($label, ['class' => 'btn btn-primary']);
}

echo Ext::stamp();

$form = ActiveForm::begin();

if ($model->ref_name && $model->isNewRecord): ?>
    <div class="form-group">
        <?= Yii::t('app', 'Referral') . ': ' . $model->ref_name; ?>
    </div>
    <?= Html::activeHiddenInput($model, 'ref_name') ?>
<?php endif;

if ($model->isNewRecord) {
    echo $form->field($model, 'name');
}

echo $form->field($model, 'email');
echo $form->field($model, 'skype');

if ('signup' == $model->scenario) {
    echo $form->field($model, 'password')->passwordInput();
    echo $form->field($model, 'repeat')->passwordInput();
}

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'account');
    echo $form->field($model, 'status')->dropDownList(User::statuses());
}

if (!$model->isNewRecord) {
    echo $form->field($model, 'phone');
    echo $form->field($model, 'forename');
    echo $form->field($model, 'surname');
}

if ($model->isNewRecord || Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'perfect');
}
else {
    echo Html::tag('div', Yii::t('app', 'To change a wallet you need <a href="{url}">write to admin</a>', [
        'url' => Url::to(['feedback/feedback/create', 'template' => 'wallet'])
    ]),
        ['class' => 'form-group']);
}

echo Html::tag('div', '* ' . Yii::t('app', 'Required fields'), ['class' => 'form-group']);

if (Yii::$app->user->isGuest) {
    echo submit(Yii::t('app', 'Signup'));
}
else {
    if ($model->isNewRecord) {
        echo submit(Yii::t('app', 'Create'));
    }
    else {
        echo submit(Yii::t('app', 'Update'));
    }
}

ActiveForm::end();

views/user/_search.php
<?php
/**
 * @link http://zenothing.com/
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'hash') ?>

    <?= $form->field($model, 'auth') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/account.php
<?php
/**
 * @link http://zenothing.com/
 */
use yii\helpers\Html;

?>
<div class="account">
    <h1><?= Yii::t('app', 'Accounts') ?></h1>
    <table class="table">
        <?php
        foreach($model as $key => $value) {
            echo Html::tag('tr',
                Html::tag('td', Yii::t('app', $key)) .
                Html::tag('td', $value)
            );
        }
        ?>
    </table>
</div>

views/user/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::$app->user->isGuest ? Yii::t('app', 'Signup') : Yii::t('app', 'Create User');
?>
<div class="user-create">
    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/user/index.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', Yii::$app->user->identity->isManager() ? 'Users' : 'Sponsors');

$columns = [
    [
        'attribute' => 'name',
        'format' => 'html',
        'value' => function($model) {
            return Html::a($model->name, ['view', 'name' => $model->name]);
        }
    ],
    'account',
    [
        'attribute' => 'perfect',
        'label' => Yii::t('app', 'Wallet')
    ],
];

if (!Yii::$app->user->getIsGuest() && Yii::$app->user->identity->isAdmin()) {
    $columns[] = 'email:email';
    $columns[] = 'skype';
    $columns[] = [
        'format' => 'html',
        'contentOptions' => ['class' => 'action'],
        'value' => function($model) {
            return implode(' ', [
                Html::a('', ['update', 'name' => $model->name], ['class' => 'glyphicon glyphicon-pencil']),
//                Html::a('', ['delete', 'id' => $model->id], ['class' => 'glyphicon glyphicon-trash'])
            ]);
        }
    ];
}
?>
<div class="user-index">
    <?php
    if ($model) {
        require 'panel.php';
    }
    ?>

    <div>
        <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <p>
            <?php
            if (Yii::$app->user->identity->isAdmin()) {
                echo Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success']);
            }
            ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => $columns,
        ]); ?>
    </div>
</div>

views/user/journal.php
<?php
/**
 * @link http://zenothing.com/
*/

/**
 * @var app\models\Record $record
 */

use app\models\User;

$info = $record->info;
if (!$info) {
    echo '';
}
elseif (isset($info['status'])) {
    echo Yii::t('app', 'Status') . ': ' . User::statuses()[$info['status']];
}
elseif (isset($info['account'])) {
    echo Yii::t('app', 'Account') . ': ' . $info['account'];
}
else {
    $key = key($info);
    echo "$key: " . $info[$key];
}

views/user/panel.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

if (!Yii::$app->user->getIsGuest()):
    ?>
    <div id='user-panel'>
        <ul>
            <li> <?=  Html::a(Yii::t('app', 'Opened Deposits'),
                    ['/bank/node/index', 'user' => $model->name], ['class' => 'btn btn-primary']) ?></li>
            <li> <?= Html::a(Yii::t('app', 'Income'),
                    ['/bank/income/index', 'user' => $model->name], ['class' => 'btn btn-primary']) ?></li>
            <?php
            if (!Yii::$app->user->isGuest) {
                if ($model->name == Yii::$app->user->identity->name || Yii::$app->user->identity->isAdmin()) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Change Password'),
                        ['/user/password', 'name' => $model->name], ['class' => 'btn btn-warning']));
                }
                ?>
                <?php
                if (Yii::$app->user->identity->isManager()) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Inform'),
                        ['/message/create', 'user' => $model->name], ['class' => 'btn btn-primary']));
                }
                ?>
                <li> <?= Html::a(Yii::t('app', 'Update'), ['/user/update', 'name' => $model->name], ['class' => 'btn btn-primary']) ?></li>
                <?php

                if ($model->name == Yii::$app->user->identity->name) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Sponsors'),
                        ['index'], ['class' => 'btn btn-primary']));
                }

                if (Yii::$app->user->identity->isAdmin()) {
                    if (empty($model->hash)) {
                        echo Html::tag('li', Html::a(Yii::t('app', 'Activate'), ['/user/email', 'code' => $model->name], ['class' => 'btn btn-primary']));
                    }
                    echo Html::tag('li', Html::a(Yii::t('app', 'Delete'), ['/user/delete', 'name' => $model->name
                    ], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                            'method' => 'post',
                        ],
                    ]));
                }
                elseif ($model->name == Yii::$app->user->identity->name) {
                    echo Html::tag('li', implode("\n", [
                        Html::beginForm('https://perfectmoney.is/api/step1.asp', 'POST'),
                        Html::hiddenInput('PAYEE_ACCOUNT', Yii::$app->perfect->wallet),
                        Html::textInput('PAYMENT_AMOUNT', 20, ['size' => 3]),
                        Html::hiddenInput('PAYEE_NAME', Yii::$app->name),
                        Html::hiddenInput('PAYMENT_UNITS', 'USD'),
                        Html::hiddenInput('PAYMENT_URL', Url::to(['/invoice/invoice/success'], true)),
                        Html::hiddenInput('NOPAYMENT_URL', Url::to(['/invoice/invoice/fail'], true)),
                        Html::hiddenInput('BAGGAGE_FIELDS', 'USER_NAME'),
                        Html::hiddenInput('USER_NAME', Yii::$app->user->identity->name),
                        Html::button(Yii::t('app', 'Pay'), [
                            'name' => 'PAYMENT_METHOD',
                            'type' => 'submit',
                            'class' => 'btn btn-primary'
                        ]),
                        Html::endForm()
                    ]));
                }
            }
            ?>
        </ul>
    </div>
<?php
endif;

views/user/request.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\widgets\Ext;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Request for password recovery');

?>
<div class="user-password">
    <?= Ext::stamp() ?>
    <h1><?= $this->title ?></h1>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/user/view.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */


$this->title = $model->name;
if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
}

$columns = [
    'name',
    'email:email',
    [
        'attribute' => 'account',
        'format' => 'html',
        'value' => Html::tag('span', $model->account) . ' ' . ($model->account > 0 ? Html::a(Yii::t('app', 'Withdraw'),
                ['invoice/invoice/create', 'amount' => (int) $model->account, 'scenario' => 'withdraw'],
                ['class' => 'btn btn-success btn-xs']) : '')
    ],
    'phone',
    'skype',
    'forename',
    'surname',
    'perfect',
];

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    $columns[] = [
        'attribute' => 'status',
        'value' => User::statuses()[$model->status]
    ];
}

$referral = Url::to(['/user/signup', 'ref_name' => $model->name], true);
?>
<div class="roompic"></div>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    require 'panel.php';
    ?>

    <div>
        <div>
            <?php
            echo Html::a(Yii::t('app', 'Referral Link'), $referral, ['class' => 'form-label']);
            ?>

            <input class="form-control" value="<?= Url::to($referral, true); ?>">
        </div>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => $columns,
        ]) ?>
    </div>
</div>